# Generated by Django 5.0 on 2026-04-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_bill_generated_by_alter_bill_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='area',
            field=models.CharField(choices=[('north', 'North Venduvazhy'), ('south', 'South Venduvazhy'), ('Substation', 'Substation'), ('Madathipady', 'Madathipady'), ('Elavanad', 'Elavanad'), ('314', '314'), ('Onnam Mile', 'Onnam Mile')], default='central', max_length=20),
        ),
    ]
