# Generated by Django 5.0 on 2026-05-08 07:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_customer_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailydelivery',
            options={'ordering': ['-date', 'route__name', 'customer__name']},
        ),
        migrations.AddField(
            model_name='dailydelivery',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.deliveryroute'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area',
            field=models.CharField(choices=[('north', 'North Venduvazhy'), ('south', 'South Venduvazhy'), ('Substation', 'Substation'), ('Vilayal', 'Vilayal'), ('Madathipady', 'Madathipady'), ('Elavanad', 'Elavanad'), ('314', '314'), ('Onnam Mile', 'Onnam Mile')], default='central', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailydelivery',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999.99'))]),
        ),
        migrations.AlterField(
            model_name='milkproduct',
            name='default_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('999999.99'))]),
        ),
    ]
